language: c++
sudo: true # for FUSE
dist: trusty

# cache:
#     directories:
#         - Qt

addons:
    apt:
        packages:
            - git
            - g++
            - make
            - autoconf
            - automake
            - libtool
            - cmake
            - pkg-config
            - libxml2-dev
            - libxslt1-dev
            - libzip-dev
            - libsqlite3-dev
            - libusb-1.0-0-dev
            - libssl-dev
            - libssh2-1-dev
            - libcurl4-openssl-dev
            # Not a subsurface dependency, but a Qt dependency
            - mesa-common-dev
            # Not a subsurface dependency, but a QtMultimedia/libdeclarative_multimedia.so dependency
            - libpulse-mainloop-glib0
            # Not a subsurface dependency, but a QtWebKit dependency
            - libhyphen-dev
            - libicu52

before_install:
    - if [ ! -e Qt/5.9.1 ] ; then
          rm -rf Qt ; mkdir -p Qt/5.9.1 ;
          wget http://subsurface-divelog.org/downloads/Qt-5.9.1.tar.xz ; tar -xJ -C Qt/5.9.1 -f Qt-5.9.1.tar.xz ;
          cd Qt/5.9.1 ; ln -s . gcc_64 ; cd .. ; ln -s 5.9.1/* . ; cd .. ;
      fi
      # TestPreferences uses gui calls, so run a xvfb so it has something to talk to
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

script:
    - export PATH=$PWD/Qt/5.9.1/bin:$PATH # Make sure correct qmake is found on the $PATH for linuxdeployqt
    - export CMAKE_PREFIX_PATH=$PWD/Qt/5.9.1/lib/cmake ;
      cd .. ;
      bash -e ./subsurface/scripts/build.sh -desktop -create-appdir -build-with-webkit
    - env CTEST_OUTPUT_ON_FAILURE=1 make -C subsurface/build check
    - # env CTEST_OUTPUT_ON_FAILURE=1 make -C subsurface/build-mobile check
    - mkdir -p appdir/usr/plugins/ ; mv appdir/usr/home/travis/build/*/subsurface/Qt/5.9.1/plugins/* appdir/usr/plugins/
    - sudo mv appdir/usr/lib/* /usr/local/lib/ # Workaround for https://github.com/probonopd/linuxdeployqt/issues/160
    - rm -rf appdir/usr/home/ appdir/usr/include/ appdir/usr/share/man/ # No need to ship developer and man files as part of the AppImage
    - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
    - chmod a+x linuxdeployqt*.AppImage
    - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
    - export LD_LIBRARY_PATH=/usr/local/lib/ # Workaround for https://github.com/probonopd/linuxdeployqt/issues/160
    - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs -qmldir=./subsurface/map-widget/ -verbose=2
    - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage -qmldir=./subsurface/map-widget/ -verbose=2
    - find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
    - curl --upload-file ./Subsurface*.AppImage https://transfer.sh/Subsurface-git.$(cd subsurface/ ; git rev-parse --short HEAD)-x86_64.AppImage
