language: c++

dist: trusty

cache:
    directories:
        - Qt

addons:
    apt:
        packages:
            - git
            - g++
            - make
            - autoconf
            - automake
            - libtool
            - cmake
            - pkg-config
            - libxml2-dev
            - libxslt1-dev
            - libzip-dev
            - libsqlite3-dev
            - libusb-1.0-0-dev
            - libssl-dev
            - libssh2-1-dev
            - libcurl4-openssl-dev
            # Not a subsurface dependency, but a Qt dependency
            - mesa-common-dev

before_install:
    - if [ ! -e Qt/5.9 ] ; then
          rm -rf Qt ;
          wget http://download.qt.io/official_releases/qt/5.9/5.9.0/qt-opensource-linux-x64-5.9.0.run ;
          chmod +x ./qt-opensource-linux-x64-5.9.0.run ;
          ./qt-opensource-linux-x64-5.9.0.run -platform minimal --script qt-installer-noninteractive.qs --no-force-installations ;
      fi
      # TestPreferences uses gui calls, so run a xvfb so it has something to talk to
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"


script:
    - export CMAKE_PREFIX_PATH=$PWD/Qt/5.9/gcc_64/lib/cmake ;
      cd .. ;
      bash -e ./subsurface/scripts/build.sh -both
    - env CTEST_OUTPUT_ON_FAILURE=1 make -C subsurface/build check
#    - env CTEST_OUTPUT_ON_FAILURE=1 make -C subsurface/build-mobile check
