name: Android Docker Image CI

on:
  push:
    paths:
    - scripts/docker/android-build-container/**
    - .github/workflows/android-dockerimage.yml

jobs:
  android-build-container:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ '5.15.2' }} # the version numbers here is based on the Qt version, the third digit is the rev of the docker image

    steps:
    - uses: actions/checkout@v1

    - name: Build the name for the docker image
      id: build_name
      run: |
        v=${{ env.VERSION }}
        b=${{ github.ref }} # -BRANCH suffix, unless the branch is master
        b=${b/refs\/heads\//}
        b=${b,,} # the name needs to be all lower case
        if [ $b = "master" ] ; then b="" ; else b="-$b" ; fi
        echo "NAME=subsurface/android-build${b}:${v}" >> $GITHUB_OUTPUT

    - name: Build and Publish Linux Docker image to Dockerhub
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name:       ${{ steps.build_name.outputs.NAME }}
        username:   ${{ secrets.DOCKER_USERNAME }}
        password:   ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: 'Dockerfile'
        workdir:    './scripts/docker/android-build-container/'
