name: Android Docker Image CI

on:
  push:
    paths:
    - scripts/docker/android-build-container/Dockerfile
    - .github/workflows/android-docker*

jobs:
  android-build-container:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ '5.13.10' }} # the version numbers here is based on the Qt version, the third digit is the rev of the docker image

    steps:
    - uses: actions/checkout@v1

    - name: Get our pre-reqs
      run: |
          cd scripts/docker/android-build-container
          bash download.sh
          sed -ie 's/^sudo/#sudo/' setup-docker.sh
          bash setup-docker.sh

    - name: set env
      run: |
        v=${{ env.VERSION }}
        echo "::set-env name=NAME::subsurface/android-build-container:${v}"

    - name: Build and Publish Linux Docker image to Dockerhub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name:       ${{ env.NAME }}
        username:   ${{ secrets.DOCKER_USERNAME }}
        password:   ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: 'Dockerfile'
        workdir:    './scripts/docker/android-build-container/'
