name: Check the Supported Dive Computer Lists

on:
  push:
    branches:
    - master
    paths:
    - libdivecomputer/src/descriptor.c
    - SupportedDivecomputers.txt
    - SupportedDivecomputers.html
    - scripts
  pull_request:
    branches:
    - master
    paths:
    - libdivecomputer/src/descriptor.c
    - SupportedDivecomputers.txt
    - SupportedDivecomputers.html
    - scripts

jobs:
  check:
    runs-on: ubuntu-24.04

    steps:
    - name: checkout sources
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Check the Supported Dive Computer Lists
      shell: bash {0}
      run: |
        perl scripts/parse-descriptor.pl SupportedDivecomputers_new.txt
        diff -u SupportedDivecomputers.txt SupportedDivecomputers_new.txt
        TXT_EXIT_CODE=$?

        perl scripts/parse-descriptor.pl SupportedDivecomputers_new.html
        diff -u SupportedDivecomputers.html SupportedDivecomputers_new.html

        if [ $? -ne 0 -o $TXT_EXIT_CODE -ne 0 ] ; then
          echo "The list of supported dive computers in libdivecomputer has changed. Please run `scripts/update-supported-divecomputer-lists.sh` and commit the resulting changes."
          exit 1
        fi
