name: Coverity Scan Linux Qt 5.9
on:
  schedule:
    - cron: '0 18 * * *' # Daily at 18:00 UTC

jobs:
  CoverityScanBuildOnUbuntu:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04

    steps:
    - name: checkout sources
      uses: actions/checkout@v1

    - name: add build dependencies
      run: |
        apt-get update
        apt-get upgrade -y
        DEBIAN_FRONTEND=noninteractive apt-get install -y -q --force-yes \
        wget curl \
        autoconf automake cmake g++ git libcrypto++-dev libcurl4-gnutls-dev \
        libgit2-dev libqt5qml5 libqt5quick5 libqt5svg5-dev \
        libqt5webkit5-dev libsqlite3-dev libssh2-1-dev libssl-dev libssl-dev \
        libtool libusb-1.0-0-dev libxml2-dev libxslt1-dev libzip-dev make \
        pkg-config qml-module-qtlocation qml-module-qtpositioning \
        qml-module-qtquick2 qt5-qmake qtchooser qtconnectivity5-dev \
        qtdeclarative5-dev qtdeclarative5-private-dev qtlocation5-dev \
        qtpositioning5-dev qtscript5-dev qttools5-dev qttools5-dev-tools \
        qtquickcontrols2-5-dev libbluetooth-dev libmtp-dev

    - name: configure environment
      env:
         SUBSURFACE_REPO_PATH: ${{ github.workspace }}
      run: |
        git config --global --add safe.directory ${SUBSURFACE_REPO_PATH}
        git config --global --add safe.directory ${SUBSURFACE_REPO_PATH}/libdivecomputer

    - name: run coverity scan
      uses: vapier/coverity-scan-action@v1
      with:
        project: Subsurface-divelog/subsurface
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}
        email: glance@acc.umu.se
        command: subsurface/scripts/build.sh -desktop -build-with-webkit
        working-directory: ${{ github.workspace }}/..
        version: $(/scripts/get-version linux)
        description: Automatic scan on github actions
