name: iOS

on:
  push:
    paths-ignore:
    - scripts/docker/**
    branches:
    - master
  pull_request:
    paths-ignore:
    - scripts/docker/**
    branches:
    - master

jobs:
  build:
    runs-on: macOS-11
    steps:
    - name: switch to Xcode 11
      run: sudo xcode-select -s "/Applications/Xcode_11.7.app"

    - name: checkout sources
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: setup Homebrew
      run: brew install autoconf automake libtool pkg-config

    - name: checkout Qt resources
      uses: actions/checkout@v4
      with:
        repository: subsurface/qt-ios
        ref: main
        path: qt-ios

    - name: set the version information
      id: version_number
      uses: ./.github/actions/manage-version
      with:
        nightly-builds-secret: ${{ secrets.NIGHTLY_BUILDS }}

    - name: build Subsurface-mobile for iOS
      env:
        VERSION: ${{ steps.version_number.outputs.version }}
      run: |
        cd ..
        git config --global --add safe.directory $GITHUB_WORKSPACE
        git config --global --add safe.directory $GITHUB_WORKSPACE/libdivecomputer
        export IOS_QT=$GITHUB_WORKSPACE/qt-ios
        echo "build for simulator"
        bash -x $GITHUB_WORKSPACE/packaging/ios/build.sh -simulator
        # We need this in order to be able to access the file and publish it
        mv build-Subsurface-mobile-Qt_5_14_1_for_iOS-Release/Release-iphonesimulator/Subsurface-mobile.app $GITHUB_WORKSPACE/Subsurface-mobile-$VERSION.app

    - name: publish artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Subsurface-iOS-${{ steps.version_number.outputs.version }}
        path: Subsurface-mobile-*.app
