name: Linux Qt 5.9
on: push

jobs:
  buildOnBionic:
    runs-on: ubuntu-18.04

    steps:
    - name: checkout sources
      uses: actions/checkout@v1

    - name: add build dependencies
      run: |
        sudo apt update
        sudo apt install -y \
        autoconf automake cmake g++ git libcrypto++-dev libcurl4-gnutls-dev \
        libgit2-dev libqt5qml5 libqt5quick5 libqt5svg5-dev \
        libqt5webkit5-dev libsqlite3-dev libssh2-1-dev libssl-dev libssl-dev \
        libtool libusb-1.0-0-dev libxml2-dev libxslt1-dev libzip-dev make \
        pkg-config qml-module-qtlocation qml-module-qtpositioning \
        qml-module-qtquick2 qt5-default qt5-qmake qtchooser qtconnectivity5-dev \
        qtdeclarative5-dev qtdeclarative5-private-dev qtlocation5-dev \
        qtpositioning5-dev qtscript5-dev qttools5-dev qttools5-dev-tools \
        qtquickcontrols2-5-dev

    - name: run build
      run: |
        cd ..
        bash -x subsurface/scripts/build.sh -desktop -build-with-webkit
